
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class JFrame extends javax.swing.JFrame {
    //Declared this variable
    double kilometers;
    
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        userInputField = new javax.swing.JTextField();
        toMilesButton = new javax.swing.JRadioButton();
        toFeetButton = new javax.swing.JRadioButton();
        toInchesButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter distance in kilometers. . .");

        userInputField.setText("0");

        buttonGroup1.add(toMilesButton);
        toMilesButton.setText("Convert to miles");
        toMilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMilesButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(toFeetButton);
        toFeetButton.setText("Convert to feet");
        toFeetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFeetButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(toInchesButton);
        toInchesButton.setText("Convert to inches");
        toInchesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toInchesButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel2.setText("Prof. Onsay is the best!");

        answerLabel.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        answerLabel.setText("The converted distance is: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(answerLabel)
                            .addComponent(toInchesButton)
                            .addComponent(toFeetButton)
                            .addComponent(toMilesButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toMilesButton)
                .addGap(18, 18, 18)
                .addComponent(toFeetButton)
                .addGap(18, 18, 18)
                .addComponent(toInchesButton)
                .addGap(18, 18, 18)
                .addComponent(answerLabel)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toMilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMilesButtonActionPerformed
       DistanceCalculator dcMiles = new DistanceCalculator();
       try {
           kilometers = Double.parseDouble(this.userInputField.getText());
           dcMiles.setKilometers(kilometers);   
       }
       catch(Exception e) {
           JOptionPane.showMessageDialog(null, "Input was not a number.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
       } 
       //If input is valid, returns a valid number of miles, if input isn't valid, returns 0
       this.answerLabel.setText("The converted distance is: " + dcMiles.toMiles());
    }//GEN-LAST:event_toMilesButtonActionPerformed

    private void toFeetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFeetButtonActionPerformed
        DistanceCalculator dcFeet = new DistanceCalculator();
        try {
           kilometers = Double.parseDouble(this.userInputField.getText());
           dcFeet.setKilometers(kilometers);
        }
        catch(Exception e) {
           JOptionPane.showMessageDialog(null, "Input was not a number.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        //If input is valid, returns a valid number of miles, if input isn't valid, returns 0
        this.answerLabel.setText("The converted distance is: " + dcFeet.toFeet());
    }//GEN-LAST:event_toFeetButtonActionPerformed

    private void toInchesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toInchesButtonActionPerformed
       DistanceCalculator dcInches = new DistanceCalculator();
       try {
          kilometers = Double.parseDouble(this.userInputField.getText());
          dcInches.setKilometers(kilometers);
        }
        catch(Exception e) {
           JOptionPane.showMessageDialog(null, "Input was not a number.", "Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        //If input is valid, returns a valid number of miles, if input isn't valid, returns 0
        this.answerLabel.setText("The converted distance is: " + dcInches.toInches());
    }//GEN-LAST:event_toInchesButtonActionPerformed

    /*private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(toMilesButton);
        bg1.add(toFeetButton);
        bg1.add(toInchesButton);
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton toFeetButton;
    private javax.swing.JRadioButton toInchesButton;
    private javax.swing.JRadioButton toMilesButton;
    private javax.swing.JTextField userInputField;
    // End of variables declaration//GEN-END:variables
}
